(to (loud-use filename)
  (newline)
  (display "-------- ")
  (display filename)
  (display " --------")
  (newline)
  (use filename))
  
(loud-use "eg/euler1")
(loud-use "eg/euler2")
(loud-use "eg/euler3")
(loud-use "eg/euler4")
(loud-use "eg/euler5")
(loud-use "eg/euler6")
(loud-use "eg/euler7")
(loud-use "eg/euler8")
