;; Run a whole lot of examples, none of which should take long.

(to (loud-use filename)
  (newline)
  (display "-------- ")
  (display filename)
  (display " --------")
  (newline)
  (use filename))

(loud-use 'memoize)
(loud-use 'parson-core)
(loud-use 'regex-match)
(loud-use 'parse)
(loud-use 'unify)

(loud-use "eg/squickcheck-examples")    ;TODO put in order below

(loud-use "test/test-export-import")
(loud-use "test/test-quasiquote")
(loud-use "test/test-strings")
(loud-use "test/test-continuations")
(loud-use "test/test-pattern-matching")
(loud-use "test/test-use")

(loud-use "test/test-hashmap")
(loud-use "test/test-hashset")
(loud-use "test/test-format")

(loud-use "test/test-bag")
(loud-use "test/test-complex")
(loud-use "test/test-cycle-write")
(loud-use "test/test-dd")
(loud-use "test/test-factor")
(loud-use "test/test-flexarray")
(loud-use "test/test-format-tables")
(loud-use "test/test-memoize")
((loud-use "test/test-pairing-heap") '())
(loud-use "test/test-parse")
(loud-use "test/test-parson")
(loud-use "test/test-parson-squared")
(loud-use "test/test-pretty-print")
(loud-use "test/test-random")
(loud-use "test/test-ratio")
(loud-use "test/test-regex-gen")
(loud-use "test/test-regex-match")
(((loud-use 'roman) 'main) '(_ "mcmlxix" "1969" "i" "0"))
(loud-use "test/test-sort")
(loud-use "test/test-ssets")
(loud-use "test/test-text")
(loud-use "test/test-text-wrap")
(loud-use "test/test-unify")

(loud-use "eg/automata/elem-ca")
(((loud-use "eg/automata/slow-life") 'smoke-test))
(((loud-use "eg/automata/trm") 'main) '(_))
(((loud-use "eg/automata/turing") 'smoke-test))
(loud-use "eg/circuitoptimizer")
(loud-use "eg/csv")
(loud-use "eg/failing")   ;; tests lib/traceback
(loud-use "eg/fizzbuzz")
(loud-use "eg/floyd-triangle")
(loud-use "test/test-2048")
(loud-use "test/test-sokoban")
(((loud-use "eg/games/tictactoe") 'quick-test))
(loud-use "test/test-huffman")
(loud-use "eg/intset1")
(loud-use "eg/intset2")
(loud-use "test/test-metaterp")   ;; misnamed: test-kernel
(loud-use "eg/lambda/compact-lambda")
(loud-use "eg/lambda/lambdacompiler")
(loud-use "eg/lambda/lambdaterp")
(loud-use "eg/lzw")
(loud-use "eg/max-path-sum")
(((loud-use "eg/oodles") 'main) '(_ "garlic"))
(loud-use "eg/sicp1")
(loud-use "eg/sicp2")
(((loud-use "eg/trivial72") 'main) '(_))
(((loud-use "eg/tusl") 'main) '(_))

