(print ("hey there" .split))
(print ("  hey  there   " .split))
(print ("     " .split))
(print ("a" .split))

(print ("" .prefix? "hey"))
(print ("" .prefix? ""))
(print ("hey" .prefix? ""))
(print ("hey" .prefix? "h"))
(print ("hey" .prefix? "x"))
(print ("hey" .prefix? "hey"))
(print ("hey" .prefix? "heyo"))

(print ("hey there" .split "||"))
(print ("hey|there" .split "||"))
(print ("hey||there" .split "||"))
(print ("hey||there||" .split "||"))
(print ("hey||th|ere|||whee" .split "||"))
(print ("hey||th|ere||||whee" .split "||"))

(print ("hey there" .replace "x" "123"))
(print ("hey" .replace "" "X"))
(print ("hey-yo-dude" .replace "-" "=="))
(print ("-hey-yo--dude-" .replace "-" "=="))
(print ("-hey-yo--dude-" .replace "-" ""))
(print ("-hey->yo->dude-" .replace "->" "(())"))
