(define (loud-load filename)
  (newline)
  (display "-------- ")
  (display filename)
  (display " --------")
  (newline)
  (use filename))
  
(loud-load "eg/euler1")
(loud-load "eg/euler2")
(loud-load "eg/euler3")
(loud-load "eg/euler4")
(loud-load "eg/euler5")
(loud-load "eg/euler7")
